"""autogenerate message

Revision ID: 46a081d6bdc6
Revises: 
Create Date: 2023-10-07 18:29:13.425044

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '46a081d6bdc6'
down_revision: Union[str, None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('tg_images',
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('tg_msg_id', sa.Uuid(), nullable=False),
    sa.Column('tg_file_path', sa.UnicodeText(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_tg_images_id'), 'tg_images', ['id'], unique=False)
    op.create_index(op.f('ix_tg_images_tg_msg_id'), 'tg_images', ['tg_msg_id'], unique=False)
    op.create_table('tg_msgs_raw',
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('tg_id', sa.Integer(), nullable=False),
    sa.Column('tg_date', sa.DateTime(), nullable=False),
    sa.Column('tg_chat', sa.String(), nullable=False),
    sa.Column('tg_chat_id', sa.Integer(), nullable=False),
    sa.Column('tg_msg', sa.UnicodeText(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_tg_msgs_raw_id'), 'tg_msgs_raw', ['id'], unique=False)
    op.create_index(op.f('ix_tg_msgs_raw_tg_chat_id'), 'tg_msgs_raw', ['tg_chat_id'], unique=False)
    op.create_index(op.f('ix_tg_msgs_raw_tg_id'), 'tg_msgs_raw', ['tg_id'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_tg_msgs_raw_tg_id'), table_name='tg_msgs_raw')
    op.drop_index(op.f('ix_tg_msgs_raw_tg_chat_id'), table_name='tg_msgs_raw')
    op.drop_index(op.f('ix_tg_msgs_raw_id'), table_name='tg_msgs_raw')
    op.drop_table('tg_msgs_raw')
    op.drop_index(op.f('ix_tg_images_tg_msg_id'), table_name='tg_images')
    op.drop_index(op.f('ix_tg_images_id'), table_name='tg_images')
    op.drop_table('tg_images')
    # ### end Alembic commands ###
